http:
  port: 80
https:
  port: 443
  tls:
    "my.warmer.com":
        key: /Users/rayliu/Desktop/key.pem
        cert: /Users/rayliu/Desktop/cert.pem
apiEndpoints:
  api:
    host: my.warmer.com
    paths: '/*'
serviceEndpoints:
  httpbin:
    url: 'http://127.0.0.1:3000'
policies:
#  - basic-auth
  - cors
  - expression
#  - key-auth
  - log
#  - oauth2
  - proxy
  - rate-limit
pipelines:
  default:
    apiEndpoints:
      - api
    policies:
    # Uncomment `key-auth:` when instructed to in the Getting Started guide.
    # - key-auth:
      - expression:
          - action:
              jscode: if(req.protocol !== 'https') res.redirect(301,'https://' + req.headers.host + req.url);
      - proxy:
          - action:
              serviceEndpoint: httpbin
              changeOrigin: false
  default1:
    apiEndpoints:
      - api1
    policies:
    # Uncomment `key-auth:` when instructed to in the Getting Started guide.
    # - key-auth:
      - expression:
          - action:
              jscode: if(req.protocol !== 'https') res.redirect(301,'https://' + req.headers.host + req.url);
      - proxy:
          - action:
              serviceEndpoint: httpbin
              changeOrigin: false
