http:
  port: 80
https:
  port: 443
  tls:
    "warmer.today":
        key: /root/ssl/warmer.today.key
        cert: /root/ssl/warmer.today.combined.pem
    "www.warmer.today":
        key: /root/ssl/warmer.today.key
        cert: /root/ssl/warmer.today.combined.pem
apiEndpoints:
  api:
    host: warmer.today
    paths: '/*'
  api1:
    host: www.warmer.today
    paths: '/*'
serviceEndpoints:
  httpbin:
    url: 'http://127.0.0.1:3000'
policies:
  - log
  - proxy
pipelines:
  default:
    apiEndpoints:
      - api
    policies:
    # Uncomment `key-auth:` when instructed to in the Getting Started guide.
    # - key-auth:
      - expression:
          - action:
              jscode: if(req.protocol !== 'https') res.redirect(301,'https://' + req.headers.host + req.url);
      - proxy:
          - action:
              serviceEndpoint: httpbin
              changeOrigin: false
  default1:
    apiEndpoints:
      - api1
    policies:
    # Uncomment `key-auth:` when instructed to in the Getting Started guide.
    # - key-auth:
      - expression:
          - action:
              jscode: if(req.protocol !== 'https') res.redirect(301,'https://' + req.headers.host + req.url);
      - proxy:
          - action:
              serviceEndpoint: httpbin
              changeOrigin: false
