http:
  port: 80
apiEndpoints:
  api:
    host: my.warmer.com
    paths: '/*'
serviceEndpoints:
  httpbin:
    url: 'http://127.0.0.1:3000'
policies:
  - log
  - proxy
pipelines:
  default:
    apiEndpoints:
      - api
    policies:
    # Uncomment `key-auth:` when instructed to in the Getting Started guide.
    # - key-auth:
      - proxy:
          - action:
              serviceEndpoint: httpbin
              changeOrigin: false
